version: "3.3"

services:
  mysql-db:
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: "todoDB"
      MYSQL_ROOT_PASSWORD: "password"

  todo-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
